### ISSUE TITLE
X86_32 missing valid Windows pattern for os.arch

### ISSUE THREAD

**Issue by vonnieda** [openpnp/opencv#1]
Reported by @phrack at https://github.com/PatternConsulting/opencv/issues/11

New versions of Oracle's 32-bit JRE for Windows often have os.arch set to x86 (x86_64 being the 64-bit version). It appears "x86" needs to be added to the list of patterns in this line: https://github.com/PatternConsulting/opencv/blob/58d13dfb7f724c041dcf8af4f62ed2a8c2da6fd1/src/main/java/nu/pattern/OpenCV.java#L65. This is causing an UnsupportedOperationException to be thrown even in cases where the OS and architecture actually are supported, e.g. on both 32-bit and 64-bit Windows with 32-bit Oracle JRE:

Caused by: java.lang.UnsupportedOperationException: Architecture "x86" is not supported. at nu.pattern.OpenCV$Arch.getCurrent(OpenCV.java:88) at nu.pattern.OpenCV.extractNativeBinary(OpenCV.java:291) at nu.pattern.OpenCV.access$100(OpenCV.java:22) at nu.pattern.OpenCV$SharedLoader.(OpenCV.java:178) at nu.pattern.OpenCV$SharedLoader.(OpenCV.java:162) at nu.pattern.OpenCV$SharedLoader$Holder.(OpenCV.java:202) ...

**Comment by vonnieda** [comment]
@phrack If you can send me a pull request that you have verified as working I can push a release tonight. I don't have a 32 bit VM to test with so that would help a lot.

**Comment by phrack** [comment]
Thanks for the heads up. It will likely take me a few days to try this because I personally don't have a Windows VM at the moment and I doubt any of the other contributors will want to drop everything to try this.

**Comment by vonnieda** [comment]
It looks like I can probably spin up a 32 bit Windows VM on AWS to test
this. I'll try that this evening and let you know.

**Comment by vonnieda** [comment]
Adding x86 does seem to fix it, and doesn't break anything else. I'll do a new release tomorrow or this weekend.

**Comment by phrack** [comment]
That's great to hear! Thank you so much for being on top of this.

**Comment by vonnieda** [comment]
v2.4.11-2 has been released to central with the suggested change. Thanks for the bug report!

**Comment by vonnieda** [comment]
@phrack Have you tried the new release? Curious if it solves the problem for you.

**Comment by phrack** [comment]
Users are reporting that it has solved the problem. Thanks!

**Comment by vonnieda** [comment]
Glad to hear it!
