### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java490 in java.library.path

### ISSUE THREAD

**Issue by heshanthenura** [openpnp/opencv#111]
My Code
```
package org.example;

import nu.pattern.OpenCV;
import org.opencv.core.Core;

public class Main {
    public static void main(String[] args) {
        OpenCV.loadLocally();
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        System.out.println("OpenCV version: " + org.opencv.core.Core.getVersionString());
    }
}
```
This is error
```

Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java490 in java.library.path: 
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2458)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
	at java.base/java.lang.System.loadLibrary(System.java:2059)
	at org.example.Main.main(Main.java:9)
```
can anyone help to fix it pls?

**Comment by heshanthenura** [comment]
fixed it

**Comment by heshanthenura** [comment]
fixed it. i didnt add dll to variable path

**Comment by christiansum** [comment]
@heshanthenura How did you do it?

**Comment by christiansum** [comment]
I found the way. 

You need to add the DLL file to the project. But you have to download and install the opencv project from the official webpage. 
For IntelliJ + Windows 11:

1. Click on File -> Project Structure ->Libraries
2. Click on "+" -> Java
3. Select the path and DLL File.  In my case "C:/opencv/490/build/java/x64/opencv_java490.dll"
4. Click Apply.
5. In the same window, choose Modules -> "ProjectName"
6. Click on "+" -> Library -> Project Library -> "x64" or the name of the library in step 3. 
7. Apply. 

That's it.
