### ISSUE TITLE
Add exposure control and codec control to OpenCV capture drivers

### ISSUE THREAD

**Issue by vonnieda** [openpnp/opencv#12]
We should take the time to go through the most common OpenCV capture drivers (dshow, v4l, avfoundation, I think) and add support, if possible, to control exposure and codec. The results should be submitted as a pull request to OpenCV.

For OpenPnP, the two biggest limiting factors for cameras with regards to OpenCV are controlling the auto exposure / exposure settings and being able to set the video codec format. Most of the OpenCV capture drivers do not support these settings, but it appears that that is due to just not having the code more than technical reasons. 

For instance, simply copying the exposure code from the iOS driver (cap_avfoundation.mm) to the Mac one (cap_avfoundation_mac.mm) seems to work fine. 

* [ ] Determine what the most common capture drivers are for Linux, Mac and Windows.
* [ ] Research the APIs used by each of the above.
* [ ] Add exposure control (CAP_PROP_EXPOSURE, CAP_PROP_AUTO_EXPOSURE) and codec setting (CAP_PROP_FOURCC) for each, or as much as possible.
* [ ] Submit results as a PR to OpenCV.

Reference Material:
https://developer.apple.com/reference/avfoundation/avcapturedevice

```
/**
 * Camera dispatching method: index is the camera number.
 * If given an index from 0 to 99, it tries to find the first
 * API that can access a given camera index.
 * Add multiples of 100 to select an API.
 */
CV_IMPL CvCapture * cvCreateCameraCapture (int index)
```

```
enum
{
    CV_CAP_ANY      =0,     // autodetect

    CV_CAP_MIL      =100,   // MIL proprietary drivers

    CV_CAP_VFW      =200,   // platform native
    CV_CAP_V4L      =200,
    CV_CAP_V4L2     =200,

    CV_CAP_FIREWARE =300,   // IEEE 1394 drivers
    CV_CAP_FIREWIRE =300,
    CV_CAP_IEEE1394 =300,
    CV_CAP_DC1394   =300,
    CV_CAP_CMU1394  =300,

    CV_CAP_STEREO   =400,   // TYZX proprietary drivers
    CV_CAP_TYZX     =400,
    CV_TYZX_LEFT    =400,
    CV_TYZX_RIGHT   =401,
    CV_TYZX_COLOR   =402,
    CV_TYZX_Z       =403,

    CV_CAP_QT       =500,   // QuickTime

    CV_CAP_UNICAP   =600,   // Unicap drivers

    CV_CAP_DSHOW    =700,   // DirectShow (via videoInput)
    CV_CAP_MSMF     =1400,  // Microsoft Media Foundation (via videoInput)

    CV_CAP_PVAPI    =800,   // PvAPI, Prosilica GigE SDK

    CV_CAP_OPENNI   =900,   // OpenNI (for Kinect)
    CV_CAP_OPENNI_ASUS =910,   // OpenNI (for Asus Xtion)

    CV_CAP_ANDROID  =1000,  // Android - not used
    CV_CAP_ANDROID_BACK =CV_CAP_ANDROID+99, // Android back camera - not used
    CV_CAP_ANDROID_FRONT =CV_CAP_ANDROID+98, // Android front camera - not used

    CV_CAP_XIAPI    =1100,   // XIMEA Camera API

    CV_CAP_AVFOUNDATION = 1200,  // AVFoundation framework for iOS (OS X Lion will have the same API)

    CV_CAP_GIGANETIX = 1300,  // Smartek Giganetix GigEVisionSDK

    CV_CAP_INTELPERC = 1500, // Intel Perceptual Computing

    CV_CAP_OPENNI2 = 1600,   // OpenNI2 (for Kinect)
    CV_CAP_GPHOTO2 = 1700,
    CV_CAP_GSTREAMER = 1800, // GStreamer
    CV_CAP_FFMPEG = 1900,    // FFMPEG
    CV_CAP_IMAGES = 2000,    // OpenCV Image Sequence (e.g. img_%02d.jpg)

    CV_CAP_ARAVIS = 2100     // Aravis GigE SDK
};
```

**Comment by CmdrDats** [comment]
oh my, this would be amazing to have control over. not having control over the exposure (or at least being able to turn it off 'auto') drives me up the wall...

**Comment by vonnieda** [comment]
Have decided to address this in the OpenPnP Capture Library which is under development. See https://github.com/openpnp/openpnp/issues/448 and https://github.com/openpnp/openpnp-capture
