### ISSUE TITLE
Javadoc documentation imported from C++

### ISSUE THREAD

**Issue by virl** [openpnp/opencv#14]
Please import Javadoc documentation for bindings from original C++ API, like https://mvnrepository.com/artifact/org.bytedeco/javacv/1.3.1 did.

**Comment by vonnieda** [comment]
JavaDocs are bundled with the Maven artifacts. Is there something specific that is missing?

**Comment by virl** [comment]
Yes, the documentation itself is missing. Javadoc works — it just doesn't contain any documentation that C++ version of OpenCV have for its classes and methods.

For example Javadoc:
```
    //
    // C++:   CascadeClassifier(String filename)
    //

    //javadoc: CascadeClassifier::CascadeClassifier(filename)
    public   CascadeClassifier(String filename)
    {
        
        nativeObj = CascadeClassifier_0(filename);
        
        return;
    }
```

C++ version:
```
CascadeClassifier::CascadeClassifier
Loads a classifier from a file.

C++: CascadeClassifier::CascadeClassifier(const String& filename)
Python: cv2.CascadeClassifier([filename]) → <CascadeClassifier object>
Parameters:	filename – Name of the file from which the classifier is loaded.
```

**Comment by vonnieda** [comment]
We just bundle the JavaDocs that are created by the OpenCV build process. In the OpenCV build there is a step that examines the C++ and generates Java files from it. If I remember correctly, this generator will only pull in the docs that are specifically marked for JavaDoc. JavaCV effectively does the same thing but they seem to do it for all the docs.

So, if we want to do this we'd need to either modify the OpenCV generator ( https://github.com/opencv/opencv/blob/master/modules/java/generator/gen_java.py ),  run something after the fact to build the documentation and insert it into the Java files or maybe run something beforehand to update the C++ files with the correct // javadoc comments. 

It's going to be a fairly difficult task, but if someone is up to it I will be more than happy to accept a pull request.

**Comment by vonnieda** [comment]
Actually, it looks like something might have changed from 2.4 to 3.2. 

Bundled docs from 2.4.13:

![screen shot 2017-01-26 at 10 39 02 am](https://cloud.githubusercontent.com/assets/1182323/22340637/ba329882-e3b3-11e6-9699-1e584a175fda.png)

Bundled docs from 3.2:

![screen shot 2017-01-26 at 10 39 21 am](https://cloud.githubusercontent.com/assets/1182323/22340653/c52c96e8-e3b3-11e6-8a11-2ba28bc5c970.png)

For anyone interested in digging into this, I would look at:

* Do the C++ files still contain the //javadoc tags?
* Does the gen_java.py script still look for them and produce the right docs?
* Are the docs getting dropped somewhere between the OpenCV build and the bundle build?

**Comment by vonnieda** [comment]
Looks like OpenCV 3 switched to Doxygen documentation and I suspect the Java generator was never updated to use it. http://docs.opencv.org/trunk/d4/db1/tutorial_documentation.html

Example of difference in docs in the source code from 2.4 to 3.2:

2.4:https://github.com/opencv/opencv/blob/2.4/modules/imgproc/include/opencv2/imgproc/imgproc.hpp#L624

3.2: https://github.com/opencv/opencv/blob/master/modules/imgproc/include/opencv2/imgproc.hpp#L2570

The upside is that if all the docs are in Doxygen format now they should be much easier to deal with. But it's still going to require changes to the OpenCV gen_java.py to get them into the source files so they can be indexed by JavaDoc.

**Comment by vonnieda** [comment]
Okay, looks like this is an OpenCV 3.2 issue: https://github.com/opencv/opencv/issues/8011

**Comment by vonnieda** [comment]
And here is the real issue: https://github.com/opencv/opencv/issues/4286

From that issue: "After moving to doxygen, documentation for python and java is not generated anymore. This process should be reworked from scratch."

So it looks like this is going to take someone working with OpenCV to get this rewritten.

**Comment by vonnieda** [comment]
Closing this as won't fix. Maintaining this distribution is already incredibly difficult and time consuming. I'm not going add more complexity to it. If OpenCV ever fixes this issue the documentation will be included automatically. So, until then...
