### ISSUE TITLE
Closeable implementation for all OpenCV classes

### ISSUE THREAD

**Issue by virl** [openpnp/opencv#16]
Currently native OpenCV objects are freed (deleted) in finalize() method on GC sweep.

But in reality (during intensive use) there happens the situation when GC haven't finalized these objects (because there is still plenty of Java Heap), but OpenCV crashes due to exhaustion of native resources.

So please implement Closeable interface (with close() method) for each OpenCV class that have Java bindings.

**Comment by virl** [comment]
Also
'''
System.gc();
System.runFinalizers();
'''
is NOT workaround, because it does not guarantee finalization running.

Properly implemented close() method is needed, that can be called several times on same object.

**Comment by virl** [comment]
Although it seems crashes are due to #17.

**Comment by vonnieda** [comment]
Hi @virl, I suggest you post this to the OpenCV issues list at https://github.com/opencv/opencv. This project is little more than just a packaging of the OpenCV bindings. The change you are looking for would have to be on OpenCV itself.
