### ISSUE TITLE
OpenCV Java bindings memory and performance issues

### ISSUE THREAD

**Issue by nicolas-rempulski** [openpnp/opencv#25]
Hi, 

I was trying your 3.2.0-1 packaging (thanks so much for that !) and I noticed once again, like any opencv java binding I ever tried, huge memory consumption. I looked around and it seems that some patches have been proposed to fix this issue with java bindings : 

https://github.com/sgjava/install-opencv#install-opencv pointing to https://github.com/sgjava/opencvmem

A patch is proposed in the same repository : https://github.com/sgjava/install-opencv/blob/master/scripts/install-opencv.sh#L80

I take a closer look and see if i can add this patch to this packaging

**Comment by vonnieda** [comment]
Hi @nicolas-rempulski, sorry for the very long response to this issue. Did you make any further progress with this? I'm working on doing new releases and am thinking about including this patch.

**Comment by vonnieda** [comment]
Alright, after reading https://github.com/sgjava/opencvmem and doing some experimentation of my own, I don't think there is any need for a change. Unfortunately, until the Java platform supports something better than finalize(), we don't have a good way to free native memory automatically. 

So, users should call Mat.release() when they are done with a Mat, and rely on finalize()  to clean up the native objects. In my testing, this works fine.
