### ISSUE TITLE
VideoCapture fails to open on any video file

### ISSUE THREAD

**Issue by lvivtotoro** [openpnp/opencv#26]
All I am doing is create a VideoCapture instance, passing the URI to the video file  
but `VideoCapture::isOpened` returns false.

This seems to happen no matter which video file I use.

**Comment by rajesh-rt** [comment]
This is working on my local PC. But when I make a executable jar and run it on any other PC, isOpened() is always returning false. Even open() is also returning false. I'm using 3.2.0-1 version.

**Comment by vonnieda** [comment]
Sorry, these builds do not include ffmpeg, which is probably required to decode video.
