### ISSUE TITLE
Current MavenCentral distribution is missing ARM package (3.2.0-1)

### ISSUE THREAD

**Issue by fakd23** [openpnp/opencv#28]
*Problem*: 
The latest JAR-File published on mavenCentral (**3.2.0-1**) is missing the **ARM package**. Hence using this dependency on an ARM architecture is missing dependencies. Building this version locally, the package is included and the library works fine. Hower I would prefer not maintaining a local build.

*Solution*: re-upload the latest build to the central repository

**Comment by JeremyKeusters** [comment]
+1 on this issue! Really in need of this!

**Comment by vonnieda** [comment]
I've just released version 3.4.2-0, please try this and see if it resolves the issue.

**Comment by JeremyKeusters** [comment]
Thanks for your work on this, but I unfortunately don't have the right testing environment anymore to test the fix.. :(

**Comment by vonnieda** [comment]
Fair enough @JeremyKeusters, thanks for getting back to me.

**Comment by Saibot900** [comment]
Is there any solution for using the ARM Package with OpenCV Version under 3, so we can use SIFT/SURF?
