### ISSUE TITLE
VideoCapture.open always returns false in Windows 10

### ISSUE THREAD

**Issue by mdagraca** [openpnp/opencv#30]
VideoCapture.open works fine with your lib version 3.2.0-1, Java 1.8.0_51 and OSX 10.11.6 but when I run it in Windows 10, it always returns false.
The code line is
`boolean open = this.videoCapture.open(cameraId); `
I tested it with cameraId 0 and 1 (integrated camera and webcam) and in both cases returns false.
When I debug in Eclipse, the camera blinks and videoCapture returns false.
The cameras works fine in Windows with other applications.
Should I add something for windows?

**Comment by league55** [comment]
+1
I try to open video.
Previously it worked with just opencv 331 jar, I'm  trying to migrate to your artifact as it is on Maven repo, but it currently just returns false

**Comment by vonnieda** [comment]
I've just released version 3.4.2-0, please try this and see if it resolves the issue.

**Comment by vonnieda** [comment]
Closed due to no response. Please reopen if you are still having this issue.
