### ISSUE TITLE
OpenCV Java JNA wrapper and memoty leaks

### ISSUE THREAD

**Issue by Artgit** [openpnp/opencv#35]
I use the following OpenCV Java JNA wrapper:

	<dependency>
		<groupId>org.openpnp</groupId>
		<artifactId>opencv</artifactId>
		<version>3.2.0-1</version>
	</dependency>

According to the application logic, I need very often to convert `Mat` to `BufferedImage` and viсe versa. In order to do this - I use the following functions:

	private BufferedImage mat2BufferedImage(Mat matrix) throws Exception {
		MatOfByte mob = new MatOfByte();
		Imgcodecs.imencode(".png", matrix, mob);
		byte ba[] = mob.toArray();
		return ImageIO.read(new ByteArrayInputStream(ba));
	}

	private Mat bufferedImageToMat(BufferedImage bi) throws IOException {
		ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
		ImageIO.write(bi, "png", byteArrayOutputStream);
		byteArrayOutputStream.flush();
		return Imgcodecs.imdecode(new MatOfByte(byteArrayOutputStream.toByteArray()), Imgcodecs.CV_LOAD_IMAGE_UNCHANGED);
	}

Right now I faced a huge memory leak during the application execution on image processing step where these functions are involved.

So my question is - do I need to manually call `MatOfByte.release()` in both of these functions(before `return` statement) in order to try to prevent the memory leak?

And the same question for the objects of the following classes:

    import org.opencv.core.MatOfPoint;
    import org.opencv.core.MatOfPoint2f;

Do I need to manually call `release()` for them also?

**Comment by vonnieda** [comment]
Sorry for the long response time on this - yes, you need to call Mat.release() for any Mat you create. OpenCV bundles a finalize method, but these often don't get called, so best practice is to release it yourself.
