### ISSUE TITLE
Develop seems to be the default branch even though it does not act as the master branch

### ISSUE THREAD

**Issue by mafagafogigante** [openpnp/opencv#4]
Correct me if I'm wrong @vonnieda, but this seems like a mistake. Usually the "default" branch is the trunk, the branch where things that were approved are going into.

However, you have develop - which makes a confusing name for a master branch - as your default one. And also, master seems to be more up-to-date than develop, which further confuses me.

**Comment by vonnieda** [comment]
Hi @mafagafogigante, the branches for the project are as expected, I think:

master: released code
develop: in development, not yet released

I tend to keep develop the default branch to indicate that this is where pull requests and new code go. I see now that your pull request that I merged the other day was to master, not develop. I had not noticed that when reviewing it.

My typical process is to merge pull requests into develop and then do releases from develop to master.

**Comment by mafagafogigante** [comment]
Then it is as one would expect (it makes sense).

I got tricked by the number of commits and some details of the tree and thought that I should request into master, as it seems to be more usually done.
