### ISSUE TITLE
Some classes are missing

### ISSUE THREAD

**Issue by leolimajr** [openpnp/opencv#41]
Hi all,
I'm using the latest 3.4.2-1 release and looks like some classes are missing.
Ex: 
```org.opencv.xfeatures2d.SIFT```
But those are part of [3.4.2](https://docs.opencv.org/3.4.2/javadoc/org/opencv/xfeatures2d/SIFT.html) javadoc.
Am I doing something wrong?

**Comment by NesbiDevelopment** [comment]
SIFT and SURF are patented algorithms which are no longer included in core opencv installations.
See: https://www.pyimagesearch.com/2015/07/16/where-did-sift-and-surf-go-in-opencv-3/

I'm not well-versed enough to say if there are licence or similar problems with including them here.
But I'd recommend using another feature extractor, like BRISK.

https://docs.opencv.org/3.4.4/javadoc/org/opencv/features2d/BRISK.html

But this of cause depends on your use case.

**Comment by vonnieda** [comment]
Yea, just as @NesbiDevelopment said. I can't justify the risk of including patented algorithms in this package.

**Comment by leolimajr** [comment]
@vonnieda @NesbiDevelopment that is more than enough argument for me.  I didn't know that. Thanks for clarifying it.
