### ISSUE TITLE
Error "Failed to get field handle to set library path" when using Java 12

### ISSUE THREAD

**Issue by martinschneider** [openpnp/opencv#44]
When calling `OpenCV.loadShared();`:

```
java.lang.ExceptionInInitializerError
	at nu.pattern.OpenCV$SharedLoader.getInstance(OpenCV.java:232)
	at nu.pattern.OpenCV.loadShared(OpenCV.java:181)

Caused by: java.lang.RuntimeException: Failed to get field handle to set library path
	at nu.pattern.OpenCV$SharedLoader.addLibraryPath(OpenCV.java:258)
	at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:206)
	at nu.pattern.OpenCV$SharedLoader.<init>(OpenCV.java:187)
	at nu.pattern.OpenCV$SharedLoader$Holder.<clinit>(OpenCV.java:228)
```

I think the problem lies [in this line](https://github.com/openpnp/opencv/blob/develop/src/main/java/nu/pattern/OpenCV.java#L252) but I'm not entirely sure how to fix it.

Is this a known issue?

**Comment by vonnieda** [comment]
Hi @martinschneider, no, this isn't a known problem. This library tends to be a little bit fragile when it comes to new Java versions, so there is probably some tweaks that need to be made. If you are able to come up with a compatible fix that would be very welcome! Otherwise, I will look at this as soon as I have some time.

Thanks,
Jason

**Comment by Maurice-Mueller** [comment]
The same error for me. When I'm testing with OpenJDK 10 it is loading but I get the following warning:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nu.pattern.OpenCV$SharedLoader (file:/home/maurice/.gradle/caches/modules-2/files-2.1/org.openpnp/opencv/3.4.2-1/fbd8f36fd1ce4e2bf0dcb12befd7d4cfc74d8d35/opencv-3.4.2-1.jar) to field java.lang.ClassLoader.usr_paths
WARNING: Please consider reporting this to the maintainers of nu.pattern.OpenCV$SharedLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/opencv_openpnp2599240055310010051/nu/pattern/opencv/linux/x86_64/libopencv_java342.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

**Comment by rlking** [comment]
Instead of `OpenCV.loadShared();` you can use `OpenCV.loadLocally();` if it's appropriate for your project. In JDK10+ they restricted the reflective access so it won't work anymore.

**Comment by AuligPromotions** [comment]
I get the same error on Java 11.0.3. Problem is I need to use Java 11, so any ideas on how to fix this?

**Comment by vonnieda** [comment]
I have some changes in the works that will hopefully solve this problem permanently. I am looking at changing how the library is loaded to the same method that JNA uses, and this should remain compatible across JDK updates.

**Comment by martinschneider** [comment]
Thanks a lot for fixing this!

**Comment by IvanLuchkin** [comment]
I am still getting this error in JDK15 with Gradle, OpenCV 4.3.0-3. I would be very thankful for some assistance. Thank you.

**Comment by vonnieda** [comment]
Two questions:

1. What operating system?
2. Can you show a log of the error happening?

Thanks,
Jason

**Comment by ejazulhaque-tomtomexternal** [comment]
While running from a BAT file I am getting the below error although running from IDE its is fine I am using Java 21 

Caused by: java.lang.RuntimeException: Failed to get field handle to set library path
	at nativecode.DllFromJarLoader$SharedLoader.addLibraryPath(DllFromJarLoader.java:241)
	at nativecode.DllFromJarLoader$SharedLoader.<init>(DllFromJarLoader.java:180)
	at nativecode.DllFromJarLoader$SharedLoader.<init>(DllFromJarLoader.java:176)
	at nativecode.DllFromJarLoader$SharedLoader$Holder.<clinit>(DllFromJarLoader.java:208)
	... 10 more
