### ISSUE TITLE
Is there any chance upgrading to openCV  4.+ ?

### ISSUE THREAD

**Issue by wujun234** [openpnp/opencv#46]

**Comment by vonnieda** [comment]
Please see comments on https://github.com/openpnp/opencv/issues/42. I'll ask the same question: Do you think we need to maintain 2.x, 3.x, and 4.x or does 4.x supplant the rest?

**Comment by wujun234** [comment]
> 
> 
> Please see comments on #42. I'll ask the same question: Do you think we need to maintain 2.x, 3.x, and 4.x or does 4.x supplant the rest?

I think keeping the old 2.x and 3.x in the maven repository is enough,  cause there must be a reason for openCV to release a huge new version.

**Comment by Delilovic** [comment]
Unfortunately version 3.4.2 does not work with object detection. the 3.4.7 (currently offered on https://opencv.org/releases/)  version fixes the issue (can confirm this my self):

https://github.com/opencv/opencv/issues/12441

**Comment by vonnieda** [comment]
Thanks @Delilovic. I'll work on getting a new release out soon.

**Comment by brainstorm** [comment]
@vonnieda I would just support 4.x, deprecating all previous ones TBH.

**Comment by Ortega-Dan** [comment]
> @vonnieda I would just support 4.x, deprecating all previous ones TBH.

yeap

**Comment by vonnieda** [comment]
4.3.0-0 is now released. Note that support has been permanently dropped for 32 bit Linux due to the difficultly of maintaining such an old version, and this release does not include the Raspberry Pi binary. This will added in a sub-release shortly.
