### ISSUE TITLE
Cannot load native binary on latest OpenSUSE or SLES release due to GLIBC 2.27 dependency

### ISSUE THREAD

**Issue by Googulator** [openpnp/opencv#53]
The latest OpenSUSE only ships GLIBC 2.26. No plans to ship 2.27 or newer in any 15.x release, and no supported way to upgrade.

**Comment by vonnieda** [comment]
Do you know if there is a way to build against an older version on a system with a newer version? I'd be happy to build against 2.26, or whatever, if I can do it on a modern distribution.

**Comment by Googulator** [comment]
Best way I found is https://github.com/wheybags/glibc_version_header.

**Comment by vonnieda** [comment]
That is a great resource - thank you! I'll give it a try and release a new version if it works.

**Comment by vonnieda** [comment]
Note to self: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Linux_compatibility_matrix

**Comment by samsieber** [comment]
Would you accept a PR moving the build workflow steps to use docker to build the linux artifacts (I'm mostly interested in the x86_64 linux builds)? I think that by building it on a CentOS 7 docker image (CentOS 7's EOL is 2024), that'll extend the glibc support all the way back to 2.17

**Comment by vonnieda** [comment]
If it fixes the issue and doesn't break anything else, that's fine with me.
It actually already builds with Docker. Can we just change the image name?

Jason

**Comment by vonnieda** [comment]
If this issue is still relevant to you, please consider submitting a pull request or reopening with further details.

Thanks,
Jason
