### ISSUE TITLE
Extra modules

### ISSUE THREAD

**Issue by bmnds** [openpnp/opencv#57]
Is it possible to load extra modules like the [Face Analysis](https://docs.opencv.org/4.3.0/db/d7c/group__face.html) one?

Great project by the way!

**Comment by sergigp** [comment]
This will be super useful tbh

**Comment by vonnieda** [comment]
I think this is now included with the latest release - 4.5.1-2. Can you give it a try?

**Comment by vatbub** [comment]
Hey :) I came here also looking for the extra modules and they don't seem to be included in 4.5.1-2 

![grafik](https://user-images.githubusercontent.com/13379225/157004053-e3a79fbe-820d-46d5-85b6-3491c611be5f.png)

**Comment by vonnieda** [comment]
If this issue is still relevant to you, please consider submitting a pull request or reopening with further details.

Thanks,
Jason
