### ISSUE TITLE
Package OpenCV 2.4.13

### ISSUE THREAD

**Issue by phrack** [openpnp/opencv#6]
2.4.13 contains v4l bug fixes that are very important on Linux.

**Comment by phrack** [comment]
@vonnieda, do you got this or should I try to shove a PR your way? May take a bit more effort because it turns out 2.4.13 doesn't compile with gcc6 for the same reason 3.1 doesn't.

**Comment by vonnieda** [comment]
@phrack I will try to get a new release done this weekend. I've just finished moving house and am working to catch up on everything now.

**Comment by phrack** [comment]
Awesome, looking forward to seeing the new package. I hope your move went well.

**Comment by vonnieda** [comment]
2.4.13-0 has now been released!

**Comment by phrack** [comment]
Awesome, thanks! Works great on Windows and Linux for me (haven't tried Mac yet).
