### ISSUE TITLE
OpenPnP on Raspberry

### ISSUE THREAD

**Issue by MrTob** [openpnp/opencv#61]
is there any solution for running OpenPnP on a Raspberry ?

**Comment by brainstorm** [comment]
Yes, experimental, over here: https://github.com/CCHS-Melbourne/openpnp-kiosk

Future releases are dependent on https://github.com/openpnp/opencv/pull/56 getting finished up so that the re-compiling and release process is seamless for all architectures.

**Comment by vonnieda** [comment]
Maven builds now include support for aarch64 / arm64 as of 4.3.0-4.
