### ISSUE TITLE
OpenCV 4.5 binding

### ISSUE THREAD

**Issue by xam-ps** [openpnp/opencv#68]
The current 4.3 version of OpenCV is not working on MacOS 11 (Big Sur). Is there already a timeline when openpnp/opencv will be released in version 4.5.x?

**Comment by vonnieda** [comment]
I've been slow about upgrading to Big Sur, so I haven't seen this. What kind of problem are you seeing?

**Comment by xam-ps** [comment]
Sorry for the confusion. Just figured out, that not Mac OS was the problem, but my Java version. After the Big Sur update my Java Version was set to 13. After setting it back to 11, openpnp/opencv is now working again. Thanks for your help anyways!
