### ISSUE TITLE
Custom Font for putText

### ISSUE THREAD

**Issue by PB-TW** [openpnp/opencv#69]
When using Imageproc.putText, only the predefined HERSHEY fonts can be used. For Python, there exists the Freetype module which allows custom TTFs to be used:

https://fireant.github.io/misc/2017/01/28/ttf-opencv.html
https://docs.opencv.org/4.3.0/d9/dfa/classcv_1_1freetype_1_1FreeType2.html

Please add support for this or is there another way of using custom fonts in Java?

**Comment by vonnieda** [comment]
I'm open to PRs that add support for this.
