### ISSUE TITLE
Missing values in TextDetectionModel resolved by upgrading to OpenCV 4.5.3

### ISSUE THREAD

**Issue by ssoper** [openpnp/opencv#76]
Hey all, just want to start out by saying how much I appreciate the incredible work you folks have put into creating an up-to-date Java interface to OpenCV. While investigating the use of TextDetectionModel_DB I kept seeing my models fail due to the value of `size` going missing in between setting it and using it in `processFrame` in [model.cpp](https://github.com/opencv/opencv/blob/4.5.1/modules/dnn/src/model.cpp#L95).

`Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.1) /Users/ssoper/workspace/opencv/opencv/opencv-4.5.1/modules/dnn/src/model.cpp:103: error: (-201:Incorrect size of input array) Input size not specified in function 'processFrame'`

After a lot of painful debugging, I was able to resolve the issue by using the steps in your `build.yml` against the latest version of [OpenCV](https://github.com/opencv/opencv/releases/tag/4.5.3) and importing as a local JAR file. I humbly ask you to kick off another build of this fantastic project so that I can import it as a Maven dependency once again. Much appreciated 🙏🏻.

**Comment by nsadeh** [comment]
Registering my support for this sentiment, running into https://github.com/openpnp/opencv/issues/78 which is another issue that gets solved by updating. Thank you!

**Comment by ssoper** [comment]
looks like there is a [new version out](https://github.com/openpnp/opencv/releases/tag/v4.5.3-0)

**Comment by vonnieda** [comment]
@ssoper That new version is posted and hopefully with help with this issue. I was not yet able to get it uploaded to Maven due to a certificate error. Still working on that.

**Comment by senolatac** [comment]
@vonnieda any update for new maven version?

**Comment by vonnieda** [comment]
Sorry for the long, long delay. 4.5.3 is up and I'm in the process of adding several newer versions.
