### ISSUE TITLE
Java crashes with exit code 134 when attempting to set t

### ISSUE THREAD

**Issue by nsadeh** [openpnp/opencv#78]
**Description**: in version 4.5.1-2 of this codebase attempting to call any of the `void` setter methods for necessary parameters as documented https://docs.opencv.org/4.5.2/javadoc/org/opencv/dnn/Model.html on a `DetectionModel` instance (a subclass of `Model`) causes Java to crash with exit code 134. Calling these methods on a `Model` object is OK, as is calling the same methods that return `Model` instead of `void` on a `DetectionModel` instance, but those give me back a `Model` object that cannot be downcasted, which doesn't have the `detect` method that I need.

**System specs**

- OS: macOS Catalina (10.15.7) 
- Version: 4.5.1-2
- JDK: both 11 and 15 (both Zulu)

**Steps to reproduce**
Using the 4.5.1-2 version of this library, instantiate a `DetectionModel` object and attempt to call `setInputParams`, any one of them. Upon running, the Java process will exit with code 134

**Notes**

- The Python version of opencv allows this call, so I am sure it is actually supposed to be supported on this class. It's also documented in the C++ docs. 
- I posted this bug to the opencv/opencv repo and they told me that an upgrade should fix the problem. Since this repo is not upgraded to the latest opencv version (per my understanding) I believe based on what they said, although they didn't ever acknowledge that this was a problem in earlier versions, an upgrade _may_ be able to fix this.

Thank you for creating this project for a Maven-hosted opencv, it's really nice!

**Comment by nsadeh** [comment]
Update: OpenCV has confirmed this gets fixed between 4.5.2 and 4.5.3 so an update would be much  appreciated :)

**Comment by vonnieda** [comment]
v4.5.3 is up. Please reopen if that doesn't resolve the problem.
