### ISSUE TITLE
Add version 4.5.3 to maven repository

### ISSUE THREAD

**Issue by csfedorov** [openpnp/opencv#80]
The last version on maven site 4.5.1-2 
https://mvnrepository.com/artifact/org.openpnp/opencv

But in git 4.5.3
https://github.com/openpnp/opencv/releases/tag/v4.5.3-0

Please, update maven repository version to 4.5.3

**Comment by leotu** [comment]
Please add version 4.5.5

https://github.com/opencv/opencv/releases/tag/4.5.5

**Comment by vonnieda** [comment]
4.5.3 has been published. Should show up in Central within a few hours.

**Comment by vonnieda** [comment]
4.5.5 has also now been published.
