### ISSUE TITLE
OpenCV 4.5.4

### ISSUE THREAD

**Issue by lynnwilliam** [openpnp/opencv#82]
Hi , OpenCV 4.5.4 now adds native support for FaceDetection and its comparison classes.

According too 
https://mvnrepository.com/artifact/org.openpnp/opencv
the highest is 4.5.1-2  from Mar 18, 2021 over 1.5 years ago.

Can we get an updated build for this please?
This is an amazing library and more people use this than you probably know.
Thank you for maintaining this repo.

**Comment by vonnieda** [comment]
4.5.4-0 has been published
