### ISSUE TITLE
when is 4.6.0 released?

### ISSUE THREAD

**Issue by lynnwilliam** [openpnp/opencv#86]
openCV openPNP maven states
https://mvnrepository.com/artifact/org.openpnp/opencv
4.5.5-1 is the latest build from Sep 01 2022

but the OpenCV release states
https://github.com/opencv/opencv/releases
4.6.0 June 20222

My apologies if I have this wrong, but is the latest version 4.6.0 for OpenCV PNP not cut ?
or if it was, are they using different internal version numbers?

**Comment by fzeng2012** [comment]
I would like to second the request for OpenCV 4.6.0.

**Comment by vonnieda** [comment]
I've just released v4.6.0-0. This is the first build with the 4.6.0 version of OpenCV, so please let me know if you experience issues. Probably will take another 12 hours or so to hit the various repos.

https://github.com/openpnp/opencv/releases/tag/v4.6.0-0

**Comment by fzeng2012** [comment]
Thank you very much!
