### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no opencv_java on Windows

### ISSUE THREAD

**Issue by blabdouze** [openpnp/opencv#88]
Hello,

I'm using the latest version (4.6.0-0) with Java 11  : 
```
<dependency>
      <groupId>org.openpnp</groupId>
      <artifactId>opencv</artifactId>
      <version>4.6.0-0</version>
    </dependency>
```

When I try to load the libraries with `nu.pattern.OpenCV.loadShared();` it extracts the native library correctly in a temp folder and add it to the java library path,  But it tries to load `opencv_java` and the native library is called `opencv_java460` resulting in the following error :  `java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path:`

I've also tried with 3.x.x and other 4.x.x version and the issue is still the same, the version number is not appended to the library name.

**Comment by vonnieda** [comment]
Please try the latest version and re-open if this is still relevant.
