### ISSUE TITLE
BarcodeDetector

### ISSUE THREAD

**Issue by Kudzushi** [openpnp/opencv#94]
Why is there no BarcodeDetector in the library?

**Comment by Kudzushi** [comment]
https://docs.opencv.org/4.x/javadoc/org/opencv/barcode/BarcodeDetector.html
When?

**Comment by vonnieda** [comment]
Don't be rude. This is open source. Add some detail to your question. 

Is the class missing? Does it normally ship with the OpenCV Java bindings? This library is simply a build and package library so if something is missing it is likely missing from the OpenCV distro.

**Comment by scrin123** [comment]
@vonnieda Hello, i am intresting this class too, But I did not find this class in repo. Could you help me to find this class?
When i visited the web site i saw some documentation's barcode but cant find Package [org.opencv.barcode]
![image](https://user-images.githubusercontent.com/24406501/228351170-d40850ea-4d31-41e9-b670-c9df8962a4ee.png)

**Comment by Kudzushi** [comment]
> Don't be rude. This is open source. Add some detail to your question.
> 
> Is the class missing? Does it normally ship with the OpenCV Java bindings? This library is simply a build and package library so if something is missing it is likely missing from the OpenCV distro.

No rudeness. I just can't figure out how I can use the above class.
