### ISSUE TITLE
Class CaptureDelegate is implemented in both 

### ISSUE THREAD

**Issue by h353617145** [openpnp/opencv#96]
objc[11566]: Class CaptureDelegate is implemented in both /private/var/folders/g4/yf97kkx551q8cn4gkvp68dj00000gn/T/opencv_openpnp8186025227809753756/nu/pattern/opencv/osx/x86_64/libopencv_java470.dylib (0x12bd29598) and /Users/suansbsnlisng/.javacpp/cache/opencv-4.5.5-1.5.7-macosx-x86_64.jar/org/bytedeco/opencv/macosx-x86_64/libopencv_videoio.405.dylib (0x13314ae60). One of the two will be used. Which one is undefined.

I need org.bytedeco.opencv to use OpenCVFrameConverter.convertToMat(), also need FaceRecognizerSF.match,how i can perfect use them?

**Comment by h353617145** [comment]
Just report an error but run together

**Comment by vonnieda** [comment]
These classes are not currently available in this library. Please see https://github.com/openpnp/opencv/issues/83 for more information.
